/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ed_project;

import java.io.IOException;

import org.json.simple.parser.ParseException;

import ed_project.Enumerations.Teams;
import ed_project.Exceptions.EmptyCollectionException;
import ed_project.Exceptions.InvalidRoute;
import ed_project.Exceptions.NoSuchElementException;
import ed_project.Exceptions.NoSuchTeamExist;
import ed_project.Exceptions.NotAcceptedValue;
import ed_project.Exceptions.NotEnoughObjects;
import ed_project.Game.Menu;
import ed_project.Game.Player;
import ed_project.GameManagement.GestaoJogadores;
import ed_project.GameManagement.Play;

/**
 * @author 8210455 Bruno Rodrigues
 * @author 8210458 João Carvalho
 */
public class Main {

    public static void main(String[] args) {
        Menu m = new Menu();

        try {
            m.mainMenu();
        } catch (NumberFormatException | IOException | NoSuchElementException | EmptyCollectionException
                | NoSuchTeamExist | NotEnoughObjects | InvalidRoute | NotAcceptedValue | ParseException e) {
            e.printStackTrace();
        }
    }
}
